# 使用 OpenJDK 作为基础镜像
FROM openjdk:11-jre-slim

# 将本地文件复制到 Docker 镜像中的 /app 目录
WORKDIR /app
COPY ./atm/build/libs/*.jar /app/app.jar

# 暴露你的应用运行的端口（假设是 8080）
EXPOSE 8090

# 设置容器启动时执行的命令
CMD ["java", "-jar", "app.jar"]
